_BASE_: "Base-SSIS.yaml"
MODEL:
  WEIGHTS: "./model_zoo/model_final.pth"
  BACKBONE:
    NAME: "build_fcos_resnet_bifpn_backbone_visd"
  RESNETS:
    DEPTH: 101
  FCOS:
    NUM_CLASSES: 2
    OFFSET: True
    CLASS_AWARE: True
    NMS_TH: 0.4 #0.6
    POST_NMS_TOPK_TEST: 15
    THRESH_WITH_CTR: False
  BiFPN:
    IN_FEATURES: ["res3", "res4", "res5"]
    OUT_CHANNELS: 160
    NORM: "SyncBN"
  CONDINST:
    MASK_OUT_STRIDE: 2
    MAX_PROPOSALS: 500
    TRACK_EMBEDDOMG_DIMENSION: 128 #256
SOLVER:
  STEPS: (40000,)
  MAX_ITER: 45000
  BASE_LR: 0.001
  IMS_PER_BATCH: 2
  CHECKPOINT_PERIOD: 5000
DATASETS:
  TRAIN: ("soba_cast_shadow_train_full",)
  TEST: ("soba_cast_shadow_val_full",)
OUTPUT_DIR: "output/SSIS_Demo"
SEED: 44904667 #24771667
